# Generated by Django 4.2.4 on 2023-08-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("garagem", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="veiculo",
            name="capa",
        ),
        migrations.AddField(
            model_name="veiculo",
            name="capa",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="+",
                to="uploader.image",
            ),
        ),
    ]
