# Generated by Django 4.2.4 on 2023-08-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("garagem", "0002_remove_veiculo_capa_veiculo_capa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo",
            name="capa",
            field=models.ManyToManyField(related_name="+", to="uploader.image"),
        ),
    ]
