# Generated by Django 4.1.7 on 2023-03-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0003_acessorio_cor_veiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acessorio',
            options={'verbose_name_plural': 'acessórios'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name_plural': 'veículos'},
        ),
    ]
