# Generated by Django 4.2.1 on 2023-06-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0005_veiculo_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="acessorio",
            field=models.ManyToManyField(
                related_name="veiculos", to="garagem.acessorio"
            ),
        ),
    ]
